"""
Report Generator - Creates forensic-style processing reports.

Markdown and JSON are written directly. PDF is rendered through matplotlib,
which is already a dependency, so producing a court-presentable report needs no
extra install.
"""

import json
import hashlib
import textwrap
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple
from datetime import datetime

import numpy as np

# A4 in inches, and the text layout that fits it
_PAGE_SIZE = (8.27, 11.69)
_LEFT_MARGIN = 0.09
_TOP = 0.95
_BOTTOM = 0.06

_STYLES = {
    #        size, weight,   family,      line height, wrap width
    'title': (16, 'bold', 'sans-serif', 0.034, 60),
    'heading': (12, 'bold', 'sans-serif', 0.028, 78),
    'body': (9, 'normal', 'sans-serif', 0.019, 100),
    'mono': (8, 'normal', 'monospace', 0.018, 95),
    'spacer': (9, 'normal', 'sans-serif', 0.012, 100),
}


class ReportGenerator:
    """Generate scientific reports of image processing chains."""

    def __init__(self, pipeline_report: Dict[str, Any], source_metadata: Dict[str, Any]):
        self.pipeline_report = pipeline_report
        self.source_metadata = source_metadata

    def to_dict(self) -> Dict[str, Any]:
        """Return full report as dictionary."""
        return {
            'report_type': 'Image Processing Chain Report',
            'generated_at': datetime.now().isoformat(),
            'source_file': self.source_metadata,
            'processing': self.pipeline_report,
        }

    def to_markdown(self) -> str:
        """Generate Markdown report (similar to Amped FIVE reports)."""
        lines = [
            "# Image Processing Report",
            "",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## Source File",
            "",
        ]

        for key, value in self.source_metadata.items():
            lines.append(f"- **{key}:** {value}")

        lines.extend([
            "",
            "## Processing Chain",
            "",
            f"Total filters applied: **{self.pipeline_report.get('filter_count', 0)}**",
            "",
        ])

        for i, step in enumerate(self.pipeline_report.get('filters', []), 1):
            lines.extend([
                f"### Step {i}: {step['name']}",
                f"- **Module:** `{step['module']}`",
                f"- **Timestamp:** {step['timestamp']}",
                "- **Parameters:**",
            ])
            for param_key, param_val in step.get('params', {}).items():
                lines.append(f"  - `{param_key}`: {param_val}")
            lines.append("")

        lines.extend([
            "## Output",
            "",
            f"- **Final shape:** {self.pipeline_report.get('current_image', {}).get('shape')}",
            f"- **Data type:** {self.pipeline_report.get('current_image', {}).get('dtype')}",
            "",
            "---",
            "*Report generated by cv-tools*",
        ])

        return '\n'.join(lines)

    def _styled_lines(self) -> List[Tuple[str, str]]:
        """
        Build the report as (text, style) pairs for the PDF renderer.

        Kept separate from ``to_markdown`` so the PDF is not littered with
        asterisks and backticks that only mean something to a Markdown reader.
        """
        lines: List[Tuple[str, str]] = [
            ('Image Processing Report', 'title'),
            (f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 'body'),
            ('', 'spacer'),
            ('Source File', 'heading'),
        ]

        for key, value in self.source_metadata.items():
            if key == 'exif' and isinstance(value, dict):
                lines.append(('exif:', 'body'))
                for tag, tag_value in value.items():
                    lines.append((f"    {tag}: {tag_value}", 'mono'))
            elif key == 'sha256':
                # Hashes go in monospace so they can be checked character by
                # character against the source file
                lines.append((f"{key}:", 'body'))
                lines.append((f"    {value}", 'mono'))
            else:
                lines.append((f"{key}: {value}", 'body'))

        lines.extend([
            ('', 'spacer'),
            ('Processing Chain', 'heading'),
            (f"Total filters applied: {self.pipeline_report.get('filter_count', 0)}", 'body'),
            ('', 'spacer'),
        ])

        for index, step in enumerate(self.pipeline_report.get('filters', []), 1):
            lines.append((f"Step {index}: {step['name']}", 'heading'))
            lines.append((f"Module: {step['module']}", 'body'))
            lines.append((f"Timestamp: {step['timestamp']}", 'body'))
            params = step.get('params', {})
            if params:
                lines.append(('Parameters:', 'body'))
                for param_key, param_value in params.items():
                    lines.append((f"    {param_key} = {param_value}", 'mono'))
            else:
                lines.append(('Parameters: defaults', 'body'))
            lines.append(('', 'spacer'))

        current = self.pipeline_report.get('current_image', {})
        lines.extend([
            ('Output', 'heading'),
            (f"Final shape: {current.get('shape')}", 'body'),
            (f"Data type: {current.get('dtype')}", 'body'),
            ('', 'spacer'),
            ('Report generated by cv-tools', 'body'),
        ])

        return lines

    def to_pdf(self, path: str) -> None:
        """
        Render the report as a paginated PDF.

        Args:
            path: Destination file

        Raises:
            RuntimeError: If matplotlib is unavailable
        """
        try:
            import matplotlib
            # Non-interactive backend: this runs headless and must never try to
            # open a window
            matplotlib.use('Agg')
            import matplotlib.pyplot as plt
            from matplotlib.backends.backend_pdf import PdfPages
        except ImportError as exc:
            raise RuntimeError(
                f"PDF export requires matplotlib: {exc}"
            ) from exc

        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with PdfPages(str(path)) as pdf:
            figure = plt.figure(figsize=_PAGE_SIZE)
            y = _TOP

            for text, style in self._styled_lines():
                size, weight, family, line_height, wrap_width = _STYLES[style]

                # Long paths and hashes must wrap rather than run off the page
                segments = textwrap.wrap(text, wrap_width) if text else ['']
                for segment in segments:
                    if y < _BOTTOM:
                        pdf.savefig(figure)
                        plt.close(figure)
                        figure = plt.figure(figsize=_PAGE_SIZE)
                        y = _TOP

                    if segment:
                        figure.text(_LEFT_MARGIN, y, segment, fontsize=size,
                                    fontweight=weight, family=family,
                                    verticalalignment='top')
                    y -= line_height

            pdf.savefig(figure)
            plt.close(figure)

    def save(self, path: str, format: str = 'markdown') -> None:
        """
        Save the report.

        Args:
            path: Destination file; the extension is corrected to match
            format: 'markdown' (or 'md'), 'json', or 'pdf'

        Raises:
            ValueError: If the format is not recognised
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        fmt = format.lower()

        if fmt == 'pdf':
            self.to_pdf(path.with_suffix('.pdf'))
            return

        if fmt in ('md', 'markdown'):
            content = self.to_markdown()
            path = path.with_suffix('.md')
        elif fmt == 'json':
            content = json.dumps(self.to_dict(), indent=2, ensure_ascii=False)
            path = path.with_suffix('.json')
        else:
            raise ValueError(f"Unknown format: {format}")

        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)


def hash_image(image: np.ndarray) -> str:
    """Compute SHA-256 hash of image data."""
    return hashlib.sha256(image.tobytes()).hexdigest()
